on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  updateRecentVods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install
      - name: Update recent vods
        run: |
          npm run cron:updateRecentVods
